# =============================================================================
# Commitlint Configuration
# =============================================================================
# Enforces conventional commit message format.
# Only overrides that differ from @commitlint/config-conventional defaults.
# Reference: https://commitlint.js.org/
# =============================================================================

extends:
  - "@commitlint/config-conventional"

rules:
  # Custom type list matching CONTRIBUTING.md (adds breaking, removes build/revert/style)
  type-enum:
    - 2
    - always
    - - feat
      - fix
      - docs
      - chore
      - ci
      - test
      - refactor
      - perf
      - breaking

  # Promote leading-blank rules from warning (default) to error
  body-leading-blank:
    - 2
    - always
  footer-leading-blank:
    - 2
    - always

  # Warn (not error) on long body lines; v20+ ignores lines containing URLs
  body-max-line-length:
    - 1
    - always
    - 100

helpUrl: "https://www.conventionalcommits.org/"
